// Safe bridge between the renderer (UI) and the Electron main process.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('overlay', {
  setIgnore: (ignore) => ipcRenderer.send('set-ignore', ignore),
  getDisplays: () => ipcRenderer.invoke('get-displays'),
  setDisplay: (id) => ipcRenderer.send('set-display', id),
  quit: () => ipcRenderer.send('quit'),
  itemsIndex: (lang) => ipcRenderer.invoke('items-index', lang),
  itemsByIndex: () => ipcRenderer.invoke('items-by-index'),
  spellsIndex: (lang) => ipcRenderer.invoke('spells-index', lang),
  mobsIndex: (lang) => ipcRenderer.invoke('mobs-index', lang),
  zones: () => ipcRenderer.invoke('zones'),
  roadsIndex: () => ipcRenderer.invoke('roads-index'),
  onRoadsOcr: (cb) => ipcRenderer.on('roads-ocr', (_e, r) => cb(r)),
  ledgerLoad: () => ipcRenderer.invoke('ledger-load'),
  ledgerSave: (data) => ipcRenderer.invoke('ledger-save', data),
  marketPrices: (itemId, quality) => ipcRenderer.invoke('market-prices', itemId, quality),
  recipesIndex: () => ipcRenderer.invoke('recipes-index'),
  enchantIndex: () => ipcRenderer.invoke('enchant-index'),
  refineIndex: () => ipcRenderer.invoke('refine-index'),
  craftExtra: () => ipcRenderer.invoke('craft-extra'),
  focusIndex: () => ipcRenderer.invoke('focus-index'),
  itemsIndexEn: () => ipcRenderer.invoke('items-index-en'),
  marketLive: (itemId, quality) => ipcRenderer.invoke('market-live', itemId, quality),
  setMarketZone: (mapId) => ipcRenderer.invoke('market-zone', mapId),
  craftPrices: (ids, location, quality) => ipcRenderer.invoke('craft-prices', ids, location, quality),
  scanPrices: (ids, locations, quality) => ipcRenderer.invoke('scan-prices', ids, locations, quality),
  history: (ids, locations, days, quality) => ipcRenderer.invoke('history', ids, locations, days, quality),
  depth: (ids, locations, quality, levels) => ipcRenderer.invoke('depth', ids, locations, quality, levels),
  topVolume: (opts) => ipcRenderer.invoke('top-volume', opts),
  markets: () => ipcRenderer.invoke('markets'),
  getVersion: () => ipcRenderer.invoke('get-version'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, s) => cb(s)),
  installUpdate: () => ipcRenderer.send('install-update'),
  // auth / token
  getToken: () => ipcRenderer.invoke('get-token'),
  authVerify: (token) => ipcRenderer.invoke('auth-verify', token),
  clearToken: () => ipcRenderer.invoke('clear-token'),
  // admin
  adminList: () => ipcRenderer.invoke('admin-list'),
  adminIssue: (name, note) => ipcRenderer.invoke('admin-issue', name, note),
  adminAction: (token, action) => ipcRenderer.invoke('admin-action', token, action),
  // npcap
  npcapStatus: () => ipcRenderer.invoke('npcap-status'),
  npcapInstall: () => ipcRenderer.invoke('npcap-install'),
});
